//------------------------------------------------------------------------------
// <auto-generated>
//  Данный файл был сгенерирован автоматически при помощи шаблона GenerateEnum 
//
//  Изменения в этом файле могут повлечь за собой некорректное поведение 
//  и будут потеряны при следующей регенерации файла.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace ETOS.DAL.Enums
{
	/// <summary>
	/// Перечисление, определяющее виды приоритетов должностей сотрудников.
	/// </summary>
	/// <remarks>Данный enum был автоматически сгенерирован из таблицы Priorities.</remarks>
	[DataContract]
	public enum Priorities : int
	{
		/// <summary>
		/// Наивысший приоритет.
		/// </summary>
		[Description("Наивысший приоритет")]
		[EnumMember]
		Highest = 1,

		/// <summary>
		/// Высокий приоритет.
		/// </summary>
		[Description("Высокий приоритет")]
		[EnumMember]
		High = 2,

		/// <summary>
		/// Средний приоритет.
		/// </summary>
		[Description("Средний приоритет")]
		[EnumMember]
		Normal = 3,

		/// <summary>
		/// Низкий приоритет.
		/// </summary>
		[Description("Низкий приоритет")]
		[EnumMember]
		Low = 4,

	}

	/// <summary>
	/// Перечисление, определяющее виды статусов заявок.
	/// </summary>
	/// <remarks>Данный enum был автоматически сгенерирован из таблицы Statuses.</remarks>
	[DataContract]
	public enum Statuses : int
	{
		/// <summary>
		/// На согласовании.
		/// </summary>
		[Display(Name = "На согласовании")]
		[EnumMember]
		OnApproval = 1,

		/// <summary>
		/// Заявка на этапе подбора автомобиля.
		/// </summary>
		[Display(Name = "Заявка на этапе подбора автомобиля")]
		[EnumMember]
		VehicleSelection = 2,

		/// <summary>
		/// Заявка отклонена.
		/// </summary>
		[Description("Заявка отклонена")]
		[EnumMember]
		WasDeclined = 3,

		/// <summary>
		/// Заявка отменена пользователем.
		/// </summary>
		[Description("Заявка отменена пользователем")]
		[EnumMember]
		WasCancelledByUser = 4,

		/// <summary>
		/// Заявка подтверждена.
		/// </summary>
		[Description("Заявка подтверждена")]
		[EnumMember]
		WasAccepted = 5,

		/// <summary>
		/// Заявка успешно завершена.
		/// </summary>
		[Description("Заявка успешно завершена")]
		[EnumMember]
		WasCompletedSuccessfully = 6,

		/// <summary>
		/// Заявка завершена неуспешно.
		/// </summary>
		[Description("Заявка завершена неуспешно")]
		[EnumMember]
		WasCompletedPoorly = 7
	}

}

